wandb_version: 1

_config:
  desc: null
  value:
    Annotation_info:
      all_label_decoder:
        '0': '1_00_0_3_11'
        '1': '1_00_0_3_12'
        '10': 3_a9_1_3_13
        '11': 3_a9_2_3_13
        '12': 3_a9_3_3_13
        '13': 3_b3_1_3_13
        '14': 3_b6_1_3_13
        '15': 3_b7_1_3_13
        '16': 3_b8_1_3_13
        '17': '4_00_0_2_12'
        '18': '4_00_0_2_13'
        '19': '4_00_0_3_12'
        '2': '2_00_0_1_13'
        '20': '4_00_0_3_13'
        '21': '4_00_0_5_12'
        '22': '5_00_0_1_12'
        '23': '5_00_0_3_12'
        '24': 5_a7_2_1_13
        '25': 5_b6_1_3_13
        '26': 5_b7_1_3_11
        '27': 5_b8_1_3_13
        '28': '6_00_0_1_24'
        '29': '6_00_0_3_24'
        '3': '2_00_0_3_13'
        '30': '6_00_0_4_24'
        '31': '6_00_0_5_24'
        '32': 6_a11_1_1_24
        '33': 6_a11_2_1_24
        '34': 6_a12_1_3_24
        '35': 6_a12_2_3_24
        '36': 6_b4_1_3_24
        '37': 6_b4_3_3_24
        '38': 6_b5_1_1_24
        '4': 2_a5_2_3_12
        '5': '3_00_0_1_13'
        '6': '3_00_0_2_12'
        '7': '3_00_0_3_11'
        '8': '3_00_0_3_12'
        '9': '3_00_0_5_11'
      all_label_encoder:
        '1_00_0_3_11': 0
        '1_00_0_3_12': 1
        '2_00_0_1_13': 2
        '2_00_0_3_13': 3
        2_a5_2_3_12: 4
        '3_00_0_1_13': 5
        '3_00_0_2_12': 6
        '3_00_0_3_11': 7
        '3_00_0_3_12': 8
        '3_00_0_5_11': 9
        3_a9_1_3_13: 10
        3_a9_2_3_13: 11
        3_a9_3_3_13: 12
        3_b3_1_3_13: 13
        3_b6_1_3_13: 14
        3_b7_1_3_13: 15
        3_b8_1_3_13: 16
        '4_00_0_2_12': 17
        '4_00_0_2_13': 18
        '4_00_0_3_12': 19
        '4_00_0_3_13': 20
        '4_00_0_5_12': 21
        '5_00_0_1_12': 22
        '5_00_0_3_12': 23
        5_a7_2_1_13: 24
        5_b6_1_3_13: 25
        5_b7_1_3_11: 26
        5_b8_1_3_13: 27
        '6_00_0_1_24': 28
        '6_00_0_3_24': 29
        '6_00_0_4_24': 30
        '6_00_0_5_24': 31
        6_a11_1_1_24: 32
        6_a11_2_1_24: 33
        6_a12_1_3_24: 34
        6_a12_2_3_24: 35
        6_b4_1_3_24: 36
        6_b4_3_3_24: 37
        6_b5_1_1_24: 38
      area_dict:
        '1': 열매
        '2': 꽃
        '3': 잎
        '4': 가지
        '5': 줄기
        '6': 뿌리
        '7': 해충
      crop_dict:
        '1': 딸기
        '2': 토마토
        '3': 파프리카
        '4': 오이
        '5': 고추
        '6': 시설포도
      disease_dict:
        '00': 정상
        a1: 딸기잿빛곰팡이병-1
        a10: 파프리카잘록병-1
        a11: 시설포도탄저병-1
        a12: 시설포도노균병-1
        a2: 딸기흰가루병-1
        a3: 오이노균병-1
        a4: 오이흰가루병-1
        a5: 토마토흰가루병-1
        a6: 토마토잿빛곰팡이병-1
        a7: 고추탄저병-1
        a8: 고추흰가루병-1
        a9: 파프리카흰가루병-1
        b1: 냉해피해-2
        b2: 열과-2
        b3: 칼슘결핍-2
        b4: 일소피해-2
        b5: 축과병-2
        b6: 다량원소결핍 (N)-2
        b7: 다량원소결핍 (P)-2
        b8: 다량원소결핍 (K)-2
      grow_dict:
        '11': 유모기
        '12': 생장기
        '13': 착화/과실기
        '21': 발아기
        '22': 개화기
        '23': 신초생장기
        '24': 과실성숙기
        '25': 수확기
        '26': 휴먼기
      human_all_label_decoder:
        '0': 고추_고추탄저병-1_중기_열매_착화/과실기
        '1': 고추_다량원소결핍 (K)-2_초기_잎_착화/과실기
        '10': 시설포도_시설포도탄저병-1_중기_열매_과실성숙기
        '11': 시설포도_시설포도탄저병-1_초기_열매_과실성숙기
        '12': 시설포도_일소피해-2_말기_잎_과실성숙기
        '13': 시설포도_일소피해-2_초기_잎_과실성숙기
        '14': 시설포도_정상_정상_가지_과실성숙기
        '15': 시설포도_정상_정상_열매_과실성숙기
        '16': 시설포도_정상_정상_잎_과실성숙기
        '17': 시설포도_정상_정상_줄기_과실성숙기
        '18': 시설포도_축과병-2_초기_열매_과실성숙기
        '19': 오이_정상_정상_꽃_생장기
        '2': 고추_다량원소결핍 (N)-2_초기_잎_착화/과실기
        '20': 오이_정상_정상_꽃_착화/과실기
        '21': 오이_정상_정상_잎_생장기
        '22': 오이_정상_정상_잎_착화/과실기
        '23': 오이_정상_정상_줄기_생장기
        '24': 토마토_정상_정상_열매_착화/과실기
        '25': 토마토_정상_정상_잎_착화/과실기
        '26': 토마토_토마토흰가루병-1_중기_잎_생장기
        '27': 파프리카_다량원소결핍 (K)-2_초기_잎_착화/과실기
        '28': 파프리카_다량원소결핍 (N)-2_초기_잎_착화/과실기
        '29': 파프리카_다량원소결핍 (P)-2_초기_잎_착화/과실기
        '3': 고추_다량원소결핍 (P)-2_초기_잎_유모기
        '30': 파프리카_정상_정상_꽃_생장기
        '31': 파프리카_정상_정상_열매_착화/과실기
        '32': 파프리카_정상_정상_잎_생장기
        '33': 파프리카_정상_정상_잎_유모기
        '34': 파프리카_정상_정상_줄기_유모기
        '35': 파프리카_칼슘결핍-2_초기_잎_착화/과실기
        '36': 파프리카_파프리카흰가루병-1_말기_잎_착화/과실기
        '37': 파프리카_파프리카흰가루병-1_중기_잎_착화/과실기
        '38': 파프리카_파프리카흰가루병-1_초기_잎_착화/과실기
        '4': 고추_정상_정상_열매_생장기
        '5': 고추_정상_정상_잎_생장기
        '6': 딸기_정상_정상_잎_생장기
        '7': 딸기_정상_정상_잎_유모기
        '8': 시설포도_시설포도노균병-1_중기_잎_과실성숙기
        '9': 시설포도_시설포도노균병-1_초기_잎_과실성숙기
      human_all_label_encoder:
        고추_고추탄저병-1_중기_열매_착화/과실기: 0
        고추_다량원소결핍 (K)-2_초기_잎_착화/과실기: 1
        고추_다량원소결핍 (N)-2_초기_잎_착화/과실기: 2
        고추_다량원소결핍 (P)-2_초기_잎_유모기: 3
        고추_정상_정상_열매_생장기: 4
        고추_정상_정상_잎_생장기: 5
        딸기_정상_정상_잎_생장기: 6
        딸기_정상_정상_잎_유모기: 7
        시설포도_시설포도노균병-1_중기_잎_과실성숙기: 8
        시설포도_시설포도노균병-1_초기_잎_과실성숙기: 9
        시설포도_시설포도탄저병-1_중기_열매_과실성숙기: 10
        시설포도_시설포도탄저병-1_초기_열매_과실성숙기: 11
        시설포도_일소피해-2_말기_잎_과실성숙기: 12
        시설포도_일소피해-2_초기_잎_과실성숙기: 13
        시설포도_정상_정상_가지_과실성숙기: 14
        시설포도_정상_정상_열매_과실성숙기: 15
        시설포도_정상_정상_잎_과실성숙기: 16
        시설포도_정상_정상_줄기_과실성숙기: 17
        시설포도_축과병-2_초기_열매_과실성숙기: 18
        오이_정상_정상_꽃_생장기: 19
        오이_정상_정상_꽃_착화/과실기: 20
        오이_정상_정상_잎_생장기: 21
        오이_정상_정상_잎_착화/과실기: 22
        오이_정상_정상_줄기_생장기: 23
        토마토_정상_정상_열매_착화/과실기: 24
        토마토_정상_정상_잎_착화/과실기: 25
        토마토_토마토흰가루병-1_중기_잎_생장기: 26
        파프리카_다량원소결핍 (K)-2_초기_잎_착화/과실기: 27
        파프리카_다량원소결핍 (N)-2_초기_잎_착화/과실기: 28
        파프리카_다량원소결핍 (P)-2_초기_잎_착화/과실기: 29
        파프리카_정상_정상_꽃_생장기: 30
        파프리카_정상_정상_열매_착화/과실기: 31
        파프리카_정상_정상_잎_생장기: 32
        파프리카_정상_정상_잎_유모기: 33
        파프리카_정상_정상_줄기_유모기: 34
        파프리카_칼슘결핍-2_초기_잎_착화/과실기: 35
        파프리카_파프리카흰가루병-1_말기_잎_착화/과실기: 36
        파프리카_파프리카흰가루병-1_중기_잎_착화/과실기: 37
        파프리카_파프리카흰가루병-1_초기_잎_착화/과실기: 38
      human_label_decoder:
        '0': 고추_고추탄저병-1_중기
        '1': 고추_다량원소결핍 (K)-2_초기
        '10': 시설포도_일소피해-2_말기
        '11': 시설포도_일소피해-2_초기
        '12': 시설포도_정상_정상
        '13': 시설포도_축과병-2_초기
        '14': 오이_정상_정상
        '15': 토마토_정상_정상
        '16': 토마토_토마토흰가루병-1_중기
        '17': 파프리카_다량원소결핍 (K)-2_초기
        '18': 파프리카_다량원소결핍 (N)-2_초기
        '19': 파프리카_다량원소결핍 (P)-2_초기
        '2': 고추_다량원소결핍 (N)-2_초기
        '20': 파프리카_정상_정상
        '21': 파프리카_칼슘결핍-2_초기
        '22': 파프리카_파프리카흰가루병-1_말기
        '23': 파프리카_파프리카흰가루병-1_중기
        '24': 파프리카_파프리카흰가루병-1_초기
        '3': 고추_다량원소결핍 (P)-2_초기
        '4': 고추_정상_정상
        '5': 딸기_정상_정상
        '6': 시설포도_시설포도노균병-1_중기
        '7': 시설포도_시설포도노균병-1_초기
        '8': 시설포도_시설포도탄저병-1_중기
        '9': 시설포도_시설포도탄저병-1_초기
      human_label_encoder:
        고추_고추탄저병-1_중기: 0
        고추_다량원소결핍 (K)-2_초기: 1
        고추_다량원소결핍 (N)-2_초기: 2
        고추_다량원소결핍 (P)-2_초기: 3
        고추_정상_정상: 4
        딸기_정상_정상: 5
        시설포도_시설포도노균병-1_중기: 6
        시설포도_시설포도노균병-1_초기: 7
        시설포도_시설포도탄저병-1_중기: 8
        시설포도_시설포도탄저병-1_초기: 9
        시설포도_일소피해-2_말기: 10
        시설포도_일소피해-2_초기: 11
        시설포도_정상_정상: 12
        시설포도_축과병-2_초기: 13
        오이_정상_정상: 14
        토마토_정상_정상: 15
        토마토_토마토흰가루병-1_중기: 16
        파프리카_다량원소결핍 (K)-2_초기: 17
        파프리카_다량원소결핍 (N)-2_초기: 18
        파프리카_다량원소결핍 (P)-2_초기: 19
        파프리카_정상_정상: 20
        파프리카_칼슘결핍-2_초기: 21
        파프리카_파프리카흰가루병-1_말기: 22
        파프리카_파프리카흰가루병-1_중기: 23
        파프리카_파프리카흰가루병-1_초기: 24
      label_decoder:
        '0': '1_00_0'
        '1': '2_00_0'
        '10': 3_b8_1
        '11': '4_00_0'
        '12': '5_00_0'
        '13': 5_a7_2
        '14': 5_b6_1
        '15': 5_b7_1
        '16': 5_b8_1
        '17': '6_00_0'
        '18': 6_a11_1
        '19': 6_a11_2
        '2': 2_a5_2
        '20': 6_a12_1
        '21': 6_a12_2
        '22': 6_b4_1
        '23': 6_b4_3
        '24': 6_b5_1
        '3': '3_00_0'
        '4': 3_a9_1
        '5': 3_a9_2
        '6': 3_a9_3
        '7': 3_b3_1
        '8': 3_b6_1
        '9': 3_b7_1
      label_encoder:
        '1_00_0': 0
        '2_00_0': 1
        2_a5_2: 2
        '3_00_0': 3
        3_a9_1: 4
        3_a9_2: 5
        3_a9_3: 6
        3_b3_1: 7
        3_b6_1: 8
        3_b7_1: 9
        3_b8_1: 10
        '4_00_0': 11
        '5_00_0': 12
        5_a7_2: 13
        5_b6_1: 14
        5_b7_1: 15
        5_b8_1: 16
        '6_00_0': 17
        6_a11_1: 18
        6_a11_2: 19
        6_a12_1: 20
        6_a12_2: 21
        6_b4_1: 22
        6_b4_3: 23
        6_b5_1: 24
      risk_dict:
        '0': 정상
        '1': 초기
        '2': 중기
        '3': 말기
      task_dict:
        '0': 정상
        '1': 병해
        '2': 생리장해
    Data_Loader:
      args:
        batch_size: 4
        data_dir: ../Prepared_Data
        is_main: true
        num_workers: 2
        sampler: over
        shuffle: true
        submit: false
        validation_split: 0.2
      type: CropDataLoader
    Dataset:
      args:
        default: train_deault_transform
        method: train_Filp_transform
      type: BaseDataset
    Height: 256
    Model_Save_Path: ../model_weight
    Prepared_Csv_Path: ../Prepared_Data
    Prepared_Data_Path: ../Prepared_Data/train
    Raw_Data_Path: ../Raw_Data/train
    Width: 256
    arch:
      args:
        class_n: 25
        rate: 0.1
      type: CNN
    is_Preprocessing: false
    loss:
      args:
        class_weight: false
      type: cross_entropy_loss
    lr_scheduler:
      args:
        gamma: 0.1
        step_size: 50
      type: StepLR
    metrics:
    - accuracy
    - f1
    n_gpu: 1
    name: Resnet50+BaseFlipAug
    train_Config:
      batch_size: 32
      dropout_rate: 0.1
      epochs: 50
      lr: 0.0001
    trainer:
      early_stop: 5
      epochs: 20
      monitor: min val_loss
      save_dir: saved/
      save_period: 1
      tensorboard: false
      verbosity: 2
    transforms_name:
      args:
        default: train_deault_transform
        method: train_Filp_transform
      type: train_transform
    wandb:
      args:
        entity: hj_ai
        project: image-classification
      use: true
_log_dir:
  desc: null
  value: saved/log/Resnet50+BaseFlipAug/0317_193256
_save_dir:
  desc: null
  value: saved/models/Resnet50+BaseFlipAug/0317_193256
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647513177
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 2
      - 13
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
log_levels:
  desc: null
  value:
    '0': 30
    '1': 20
    '2': 10
    '3': 40
resume:
  desc: null
  value: null
